---
  - name: Setup sshkey directory
    hosts: localhost
    connection: local
    tasks:

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: u=rwx,g=,o=
      
