---
  - name: Install cargo packages
    hosts: localhost
    connection: local
    any_errors_fatal: true
    tasks:

      - name: Set rustup toolchain to nightly
        ansible.builtin.command: /usr/sbin/rustup default nightly

      - name: Install sccache
        community.general.cargo:
          name: sccache
          state: latest

      - name: Install bob-nvim
        community.general.cargo:
          name: bob-nvim
          state: latest

