---
  - name: Update dotfile configs and stow them
    hosts: localhost
    connection: local
    tasks:

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: u=rwx,g=,o=
      
    - name: Example clone of a single branch
      ansible.builtin.git:
        accept_hostkey: true
        repo: git@github.com:Natombrio/.dotfiles.git
        dest: .dotfiles/config
        single_branch: yes
        version: main
        

