---
  - name: Install packages from pacman
    hosts: localhost
    connection: local
    tasks:

      - name: Install software
        pacman:
          update_cache: yes
          name: 
            - clang
            - git
            - openssh
            - ripgrep
            - pyright
            - rustup
            - pkgconf
            - man-db
            - tmux
            - stow
            - nushell
            - fd
            - bat
            - bacon
            - skim
            - starship
            - base-devel
            - make
            - npm
            - unzip
            - zoxide
            - python-pip
          state: latest
