theme = "base16_transparent"

[editor]
cursorcolumn = true
cursorline = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
idle-timeout = 200
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "workspace-diagnostics"]
center = ["file-base-name", "file-modification-indicator"]
right = ["diagnostics", "position"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"


[keys.normal]
X = "extend_line_above"
"ä" = "command_mode"
C-a = ["collapse_selection", "keep_primary_selection"]
# Muscle memory
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
G = "goto_file_end"
"%" = "match_brackets"

# Uncanny valley stuff, this makes w and b behave as they do Vim
# w = ["move_next_word_start", "move_char_right", "collapse_selection"]
# W = ["move_next_long_word_start", "move_char_right", "collapse_selection"]
# e = ["move_next_word_end", "collapse_selection"]
# E = ["move_next_long_word_end", "collapse_selection"]
# b = ["move_prev_word_start", "collapse_selection"]
# B = ["move_prev_long_word_start", "collapse_selection"]

i = ["collapse_selection", "insert_mode", "collapse_selection"]
a = ["collapse_selection","append_mode", "collapse_selection"]

# Undoing the 'd' + motion commands restores the selection which is annoying
u = ["undo", "collapse_selection"]

[keys.insert]
C-a = ["collapse_selection", "normal_mode"]

[keys.select]
C-a = ["collapse_selection", "keep_primary_selection", "normal_mode"]
# Muscle memory
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
G = "goto_file_end"
"%" = "match_brackets"

