theme = "base16_transparent"

[editor]
cursorcolumn = true
cursorline = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
idle-timeout = 200
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "workspace-diagnostics"]
center = ["file-base-name", "file-modification-indicator"]
right = ["diagnostics", "position"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[keys.insert]
C-a = "normal_mode"

[keys.normal]
X = "extend_line_above"
"ä" = "command_mode"

[keys.normal.g]
G = "goto_file_end"
