vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.clipboard = 'unnamed'
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.updatetime = 50
vim.opt.smartindent = true
vim.opt.wrap = false
vim.opt.hlsearch = true
vim.opt.hidden = true
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.scrolloff = 10
vim.opt.signcolumn = 'yes'
vim.opt.colorcolumn = '88'
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.belloff = 'all'
vim.opt.laststatus = 3
vim.opt.mouse = 'nvi'
vim.o.undofile = true
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.g.netrw_banner=0
vim.g.language = "en_US"
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.termguicolors = true
